services:
  wordpress:
    image: wordpress:latest
    ports:
      - 8000:80
    volumes:
      - ./php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./src:/var/www/html # Full wordpress project      
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    depends_on:
      - db     

  db:
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
      - ./src:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootwordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: rootwordpress
    depends_on:
      - db      

  composer:
    image: composer/composer
    working_dir: /var/www/html
    restart: 'no'
    volumes:
      - ./src:/var/www/html:rw,cached      
 
volumes:
  db_data: {}